name: rentalworks
description: A Rentalworks API library for Dart developers.
version: 1.0.0
homepage: https://github.com/point-source/dart_rentalworks

environment:
  sdk: ">=2.12.0 <3.0.0"

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.14.4
