name: lasso
description: A Lasso API library for Dart developers.
version: 1.0.0
homepage: https://github.com/point-source/dart_lasso

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  chopper: ^4.0.1

dev_dependencies:
  lints: ^1.0.1
  test: ^1.14.4
  build_runner: ^2.0.6
  chopper_generator: ^4.0.1
  json_annotation: ^4.1.0
  json_serializable: ^4.1.3
  swagger_dart_code_generator: ^2.0.7

dependency_overrides:
  analyzer: ^2.0.0
